### ISSUE TITLE
Error with bundle with python 3.3

### ISSUE THREAD

**Issue by Jarod42** [oclint/oclint#94]
```
Traceback (most recent call last):
  File "bundle", line 12, in <module>
    from oclintscripts import version
ImportError: cannot import name version
```

it works correctly with python 2.7

To fix it (work with 2.7 and 3.3), I replace in oclintscripts/version.py
    import path
by
    import oclintscripts.path as path
